# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
from tast.cros.services.cros.printer import chrome_printing_service_pb2 as tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in tast/cros/services/cros/printer/chrome_printing_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ChromePrintingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetPrinters = channel.unary_unary(
                '/tast.cros.printer.ChromePrintingService/GetPrinters',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrintersResponse.FromString,
                _registered_method=True)
        self.SubmitJob = channel.unary_unary(
                '/tast.cros.printer.ChromePrintingService/SubmitJob',
                request_serializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.SubmitJobRequest.SerializeToString,
                response_deserializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.SubmitJobResponse.FromString,
                _registered_method=True)
        self.GetJobStatus = channel.unary_unary(
                '/tast.cros.printer.ChromePrintingService/GetJobStatus',
                request_serializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetJobStatusRequest.SerializeToString,
                response_deserializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetJobStatusResponse.FromString,
                _registered_method=True)
        self.CancelJob = channel.unary_unary(
                '/tast.cros.printer.ChromePrintingService/CancelJob',
                request_serializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.CancelJobRequest.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)
        self.GetPrinterInfo = channel.unary_unary(
                '/tast.cros.printer.ChromePrintingService/GetPrinterInfo',
                request_serializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrinterInfoRequest.SerializeToString,
                response_deserializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrinterInfoResponse.FromString,
                _registered_method=True)
        self.Close = channel.unary_unary(
                '/tast.cros.printer.ChromePrintingService/Close',
                request_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                _registered_method=True)


class ChromePrintingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetPrinters(self, request, context):
        """GetPrinters returns the list of available printers using the
        chrome.printing.getPrinters API method.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitJob(self, request, context):
        """SubmitJob calls the chrome.printing.submitJob() API method. It takes a
        submitJobRequest and returns the jobID of the submitted job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetJobStatus(self, request, context):
        """GetJobStatus calls the chrome.printing.getJobStatus(jobId) API method, it
        takes the jobId returned by SubmitJob. Returns an error if the jobId
        doesn't exist, otherwise returns the status of the job.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CancelJob(self, request, context):
        """CancelJob calls the chrome.printing.CancelJob(jobId) to cancel a submitted
        job. It takes the jobId returned by SubmitJob, returns an error if there
        are no active print jobs with the given jobId.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPrinterInfo(self, request, context):
        """GetPrinterInfo retrieves the capabilities and status for a specified
        printer.

        Takes a GetPrinterInfoRequest containing the printer's ID and returns a
        GetPrinterInfoResponse with its printer status and capabilities.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Close(self, request, context):
        """Close releases the Chrome instance initialized after calling any other
        ChromePrintingService method.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChromePrintingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetPrinters': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrinters,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrintersResponse.SerializeToString,
            ),
            'SubmitJob': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitJob,
                    request_deserializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.SubmitJobRequest.FromString,
                    response_serializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.SubmitJobResponse.SerializeToString,
            ),
            'GetJobStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetJobStatus,
                    request_deserializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetJobStatusRequest.FromString,
                    response_serializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetJobStatusResponse.SerializeToString,
            ),
            'CancelJob': grpc.unary_unary_rpc_method_handler(
                    servicer.CancelJob,
                    request_deserializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.CancelJobRequest.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'GetPrinterInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPrinterInfo,
                    request_deserializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrinterInfoRequest.FromString,
                    response_serializer=tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrinterInfoResponse.SerializeToString,
            ),
            'Close': grpc.unary_unary_rpc_method_handler(
                    servicer.Close,
                    request_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tast.cros.printer.ChromePrintingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tast.cros.printer.ChromePrintingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChromePrintingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetPrinters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tast.cros.printer.ChromePrintingService/GetPrinters',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrintersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tast.cros.printer.ChromePrintingService/SubmitJob',
            tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.SubmitJobRequest.SerializeToString,
            tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.SubmitJobResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetJobStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tast.cros.printer.ChromePrintingService/GetJobStatus',
            tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetJobStatusRequest.SerializeToString,
            tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetJobStatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CancelJob(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tast.cros.printer.ChromePrintingService/CancelJob',
            tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.CancelJobRequest.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPrinterInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tast.cros.printer.ChromePrintingService/GetPrinterInfo',
            tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrinterInfoRequest.SerializeToString,
            tast_dot_cros_dot_services_dot_cros_dot_printer_dot_chrome__printing__service__pb2.GetPrinterInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Close(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tast.cros.printer.ChromePrintingService/Close',
            google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
