"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""

import builtins
import collections.abc
import google.protobuf.descriptor
import google.protobuf.internal.containers
import google.protobuf.internal.enum_type_wrapper
import google.protobuf.message
import google.protobuf.struct_pb2
import sys
import typing

if sys.version_info >= (3, 10):
    import typing as typing_extensions
else:
    import typing_extensions

DESCRIPTOR: google.protobuf.descriptor.FileDescriptor

class _JobStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _JobStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_JobStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    JOB_STATUS_UNSPECIFIED: _JobStatus.ValueType  # 0
    PENDING: _JobStatus.ValueType  # 1
    IN_PROGRESS: _JobStatus.ValueType  # 2
    FAILED: _JobStatus.ValueType  # 3
    CANCELED: _JobStatus.ValueType  # 4
    PRINTED: _JobStatus.ValueType  # 5

class JobStatus(_JobStatus, metaclass=_JobStatusEnumTypeWrapper): ...

JOB_STATUS_UNSPECIFIED: JobStatus.ValueType  # 0
PENDING: JobStatus.ValueType  # 1
IN_PROGRESS: JobStatus.ValueType  # 2
FAILED: JobStatus.ValueType  # 3
CANCELED: JobStatus.ValueType  # 4
PRINTED: JobStatus.ValueType  # 5
global___JobStatus = JobStatus

class _PrinterStatus:
    ValueType = typing.NewType("ValueType", builtins.int)
    V: typing_extensions.TypeAlias = ValueType

class _PrinterStatusEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[_PrinterStatus.ValueType], builtins.type):
    DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
    PRINTER_STATUS_UNKNOWN: _PrinterStatus.ValueType  # 0
    PRINTER_STATUS_AVAILABLE: _PrinterStatus.ValueType  # 1
    PRINTER_STATUS_DOOR_OPEN: _PrinterStatus.ValueType  # 2
    PRINTER_STATUS_TRAY_MISSING: _PrinterStatus.ValueType  # 3
    PRINTER_STATUS_OUT_OF_INK: _PrinterStatus.ValueType  # 4
    PRINTER_STATUS_OUT_OF_PAPER: _PrinterStatus.ValueType  # 5
    PRINTER_STATUS_OUTPUT_FULL: _PrinterStatus.ValueType  # 6
    PRINTER_STATUS_PAPER_JAM: _PrinterStatus.ValueType  # 7
    PRINTER_STATUS_STOPPED: _PrinterStatus.ValueType  # 8
    PRINTER_STATUS_GENERIC_ISSUE: _PrinterStatus.ValueType  # 9
    PRINTER_STATUS_UNREACHABLE: _PrinterStatus.ValueType  # 10
    PRINTER_STATUS_EXPIRED_CERTIFICATE: _PrinterStatus.ValueType  # 11

class PrinterStatus(_PrinterStatus, metaclass=_PrinterStatusEnumTypeWrapper):
    """See Chrome Printing API PrinterStatus:
    https://developer.chrome.com/docs/extensions/reference/api/printing#type-PrinterStatus
    """

PRINTER_STATUS_UNKNOWN: PrinterStatus.ValueType  # 0
PRINTER_STATUS_AVAILABLE: PrinterStatus.ValueType  # 1
PRINTER_STATUS_DOOR_OPEN: PrinterStatus.ValueType  # 2
PRINTER_STATUS_TRAY_MISSING: PrinterStatus.ValueType  # 3
PRINTER_STATUS_OUT_OF_INK: PrinterStatus.ValueType  # 4
PRINTER_STATUS_OUT_OF_PAPER: PrinterStatus.ValueType  # 5
PRINTER_STATUS_OUTPUT_FULL: PrinterStatus.ValueType  # 6
PRINTER_STATUS_PAPER_JAM: PrinterStatus.ValueType  # 7
PRINTER_STATUS_STOPPED: PrinterStatus.ValueType  # 8
PRINTER_STATUS_GENERIC_ISSUE: PrinterStatus.ValueType  # 9
PRINTER_STATUS_UNREACHABLE: PrinterStatus.ValueType  # 10
PRINTER_STATUS_EXPIRED_CERTIFICATE: PrinterStatus.ValueType  # 11
global___PrinterStatus = PrinterStatus

@typing.final
class GetPrintersResponse(google.protobuf.message.Message):
    """GetPrintersResponse contains a list of available printers."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRINTERS_FIELD_NUMBER: builtins.int
    @property
    def printers(self) -> google.protobuf.internal.containers.RepeatedCompositeFieldContainer[global___Printer]: ...
    def __init__(
        self,
        *,
        printers: collections.abc.Iterable[global___Printer] | None = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["printers", b"printers"]) -> None: ...

global___GetPrintersResponse = GetPrintersResponse

@typing.final
class Printer(google.protobuf.message.Message):
    """Printer represents a single printer with its properties."""

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    DESCRIPTION_FIELD_NUMBER: builtins.int
    ID_FIELD_NUMBER: builtins.int
    ISDEFAULT_FIELD_NUMBER: builtins.int
    NAME_FIELD_NUMBER: builtins.int
    URI_FIELD_NUMBER: builtins.int
    RECENTLYUSEDRANK_FIELD_NUMBER: builtins.int
    SOURCE_FIELD_NUMBER: builtins.int
    description: builtins.str
    id: builtins.str
    isDefault: builtins.bool
    name: builtins.str
    uri: builtins.str
    recentlyUsedRank: builtins.int
    source: builtins.str
    def __init__(
        self,
        *,
        description: builtins.str = ...,
        id: builtins.str = ...,
        isDefault: builtins.bool = ...,
        name: builtins.str = ...,
        uri: builtins.str = ...,
        recentlyUsedRank: builtins.int = ...,
        source: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["description", b"description", "id", b"id", "isDefault", b"isDefault", "name", b"name", "recentlyUsedRank", b"recentlyUsedRank", "source", b"source", "uri", b"uri"]) -> None: ...

global___Printer = Printer

@typing.final
class SubmitJobRequest(google.protobuf.message.Message):
    """---------------------------------------------------------------------------
    NOTE: The following messages related to the print ticket (Job, Ticket, Print,
    etc.) use snake_case for their field names (e.g., `media_size`).
    This is a deliberate choice to directly map to the JSON format expected by
    the chrome.printing.submitJob API, simplifying integration.
    Cloud Job Ticket: https://developers.google.com/cloud-print/docs/cdd#cjt

    Other messages in this file follow the standard camelCase convention.
    ---------------------------------------------------------------------------
    """

    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOB_FIELD_NUMBER: builtins.int
    @property
    def job(self) -> global___Job: ...
    def __init__(
        self,
        *,
        job: global___Job | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["job", b"job"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["job", b"job"]) -> None: ...

global___SubmitJobRequest = SubmitJobRequest

@typing.final
class Job(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    TITLE_FIELD_NUMBER: builtins.int
    TICKET_FIELD_NUMBER: builtins.int
    CONTENTTYPE_FIELD_NUMBER: builtins.int
    DOCUMENT_FIELD_NUMBER: builtins.int
    PRINTERID_FIELD_NUMBER: builtins.int
    title: builtins.str
    contentType: builtins.str
    document: builtins.str
    printerId: builtins.str
    @property
    def ticket(self) -> global___Ticket: ...
    def __init__(
        self,
        *,
        title: builtins.str = ...,
        ticket: global___Ticket | None = ...,
        contentType: builtins.str = ...,
        document: builtins.str = ...,
        printerId: builtins.str = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["ticket", b"ticket"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["contentType", b"contentType", "document", b"document", "printerId", b"printerId", "ticket", b"ticket", "title", b"title"]) -> None: ...

global___Job = Job

@typing.final
class Ticket(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    PRINT_FIELD_NUMBER: builtins.int
    version: builtins.str
    @property
    def print(self) -> global___Print: ...
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        print: global___Print | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["print", b"print"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["print", b"print", "version", b"version"]) -> None: ...

global___Ticket = Ticket

@typing.final
class Print(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    MEDIA_SIZE_FIELD_NUMBER: builtins.int
    COPIES_FIELD_NUMBER: builtins.int
    PAGE_ORIENTATION_FIELD_NUMBER: builtins.int
    COLOR_FIELD_NUMBER: builtins.int
    FIT_TO_PAGE_FIELD_NUMBER: builtins.int
    COLLATE_FIELD_NUMBER: builtins.int
    DUPLEX_FIELD_NUMBER: builtins.int
    DPI_FIELD_NUMBER: builtins.int
    REVERSE_ORDER_FIELD_NUMBER: builtins.int
    @property
    def media_size(self) -> global___MediaSize: ...
    @property
    def copies(self) -> global___Copies: ...
    @property
    def page_orientation(self) -> global___PageOrientation: ...
    @property
    def color(self) -> global___Color: ...
    @property
    def fit_to_page(self) -> global___FitToPage: ...
    @property
    def collate(self) -> global___Collate: ...
    @property
    def duplex(self) -> global___Duplex: ...
    @property
    def dpi(self) -> global___Dpi: ...
    @property
    def reverse_order(self) -> global___ReverseOrder: ...
    def __init__(
        self,
        *,
        media_size: global___MediaSize | None = ...,
        copies: global___Copies | None = ...,
        page_orientation: global___PageOrientation | None = ...,
        color: global___Color | None = ...,
        fit_to_page: global___FitToPage | None = ...,
        collate: global___Collate | None = ...,
        duplex: global___Duplex | None = ...,
        dpi: global___Dpi | None = ...,
        reverse_order: global___ReverseOrder | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["collate", b"collate", "color", b"color", "copies", b"copies", "dpi", b"dpi", "duplex", b"duplex", "fit_to_page", b"fit_to_page", "media_size", b"media_size", "page_orientation", b"page_orientation", "reverse_order", b"reverse_order"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["collate", b"collate", "color", b"color", "copies", b"copies", "dpi", b"dpi", "duplex", b"duplex", "fit_to_page", b"fit_to_page", "media_size", b"media_size", "page_orientation", b"page_orientation", "reverse_order", b"reverse_order"]) -> None: ...

global___Print = Print

@typing.final
class Color(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Color._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TYPE_UNSPECIFIED: Color._Type.ValueType  # 0
        STANDARD_MONOCHROME: Color._Type.ValueType  # 1
        STANDARD_COLOR: Color._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    TYPE_UNSPECIFIED: Color.Type.ValueType  # 0
    STANDARD_MONOCHROME: Color.Type.ValueType  # 1
    STANDARD_COLOR: Color.Type.ValueType  # 2

    TYPE_FIELD_NUMBER: builtins.int
    type: global___Color.Type.ValueType
    def __init__(
        self,
        *,
        type: global___Color.Type.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_type", b"_type", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_type", b"_type", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_type", b"_type"]) -> typing.Literal["type"] | None: ...

global___Color = Color

@typing.final
class PageOrientation(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[PageOrientation._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        TYPE_UNSPECIFIED: PageOrientation._Type.ValueType  # 0
        PORTRAIT: PageOrientation._Type.ValueType  # 1
        LANDSCAPE: PageOrientation._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    TYPE_UNSPECIFIED: PageOrientation.Type.ValueType  # 0
    PORTRAIT: PageOrientation.Type.ValueType  # 1
    LANDSCAPE: PageOrientation.Type.ValueType  # 2

    TYPE_FIELD_NUMBER: builtins.int
    type: global___PageOrientation.Type.ValueType
    def __init__(
        self,
        *,
        type: global___PageOrientation.Type.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_type", b"_type", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_type", b"_type", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_type", b"_type"]) -> typing.Literal["type"] | None: ...

global___PageOrientation = PageOrientation

@typing.final
class Copies(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COPIES_FIELD_NUMBER: builtins.int
    copies: builtins.int
    def __init__(
        self,
        *,
        copies: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["copies", b"copies"]) -> None: ...

global___Copies = Copies

@typing.final
class MediaSize(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HEIGHT_MICRONS_FIELD_NUMBER: builtins.int
    WIDTH_MICRONS_FIELD_NUMBER: builtins.int
    height_microns: builtins.int
    width_microns: builtins.int
    def __init__(
        self,
        *,
        height_microns: builtins.int = ...,
        width_microns: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["height_microns", b"height_microns", "width_microns", b"width_microns"]) -> None: ...

global___MediaSize = MediaSize

@typing.final
class FitToPage(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[FitToPage._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NO_FITTING: FitToPage._Type.ValueType  # 0
        FIT_TO_PAGE: FitToPage._Type.ValueType  # 1
        GROW_TO_PAGE: FitToPage._Type.ValueType  # 2
        SHRINK_TO_PAGE: FitToPage._Type.ValueType  # 3
        FILL_PAGE: FitToPage._Type.ValueType  # 4
        AUTO: FitToPage._Type.ValueType  # 5

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    NO_FITTING: FitToPage.Type.ValueType  # 0
    FIT_TO_PAGE: FitToPage.Type.ValueType  # 1
    GROW_TO_PAGE: FitToPage.Type.ValueType  # 2
    SHRINK_TO_PAGE: FitToPage.Type.ValueType  # 3
    FILL_PAGE: FitToPage.Type.ValueType  # 4
    AUTO: FitToPage.Type.ValueType  # 5

    TYPE_FIELD_NUMBER: builtins.int
    type: global___FitToPage.Type.ValueType
    def __init__(
        self,
        *,
        type: global___FitToPage.Type.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_type", b"_type", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_type", b"_type", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_type", b"_type"]) -> typing.Literal["type"] | None: ...

global___FitToPage = FitToPage

@typing.final
class Collate(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    COLLATE_FIELD_NUMBER: builtins.int
    collate: builtins.bool
    def __init__(
        self,
        *,
        collate: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_collate", b"_collate", "collate", b"collate"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_collate", b"_collate", "collate", b"collate"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_collate", b"_collate"]) -> typing.Literal["collate"] | None: ...

global___Collate = Collate

@typing.final
class Duplex(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    class _Type:
        ValueType = typing.NewType("ValueType", builtins.int)
        V: typing_extensions.TypeAlias = ValueType

    class _TypeEnumTypeWrapper(google.protobuf.internal.enum_type_wrapper._EnumTypeWrapper[Duplex._Type.ValueType], builtins.type):
        DESCRIPTOR: google.protobuf.descriptor.EnumDescriptor
        NO_DUPLEX: Duplex._Type.ValueType  # 0
        LONG_EDGE: Duplex._Type.ValueType  # 1
        SHORT_EDGE: Duplex._Type.ValueType  # 2

    class Type(_Type, metaclass=_TypeEnumTypeWrapper): ...
    NO_DUPLEX: Duplex.Type.ValueType  # 0
    LONG_EDGE: Duplex.Type.ValueType  # 1
    SHORT_EDGE: Duplex.Type.ValueType  # 2

    TYPE_FIELD_NUMBER: builtins.int
    type: global___Duplex.Type.ValueType
    def __init__(
        self,
        *,
        type: global___Duplex.Type.ValueType | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_type", b"_type", "type", b"type"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_type", b"_type", "type", b"type"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_type", b"_type"]) -> typing.Literal["type"] | None: ...

global___Duplex = Duplex

@typing.final
class Dpi(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    HORIZONTAL_DPI_FIELD_NUMBER: builtins.int
    VERTICAL_DPI_FIELD_NUMBER: builtins.int
    horizontal_dpi: builtins.int
    vertical_dpi: builtins.int
    def __init__(
        self,
        *,
        horizontal_dpi: builtins.int = ...,
        vertical_dpi: builtins.int = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["horizontal_dpi", b"horizontal_dpi", "vertical_dpi", b"vertical_dpi"]) -> None: ...

global___Dpi = Dpi

@typing.final
class ReverseOrder(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    REVERSE_ORDER_FIELD_NUMBER: builtins.int
    reverse_order: builtins.bool
    def __init__(
        self,
        *,
        reverse_order: builtins.bool | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["_reverse_order", b"_reverse_order", "reverse_order", b"reverse_order"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["_reverse_order", b"_reverse_order", "reverse_order", b"reverse_order"]) -> None: ...
    def WhichOneof(self, oneof_group: typing.Literal["_reverse_order", b"_reverse_order"]) -> typing.Literal["reverse_order"] | None: ...

global___ReverseOrder = ReverseOrder

@typing.final
class SubmitJobResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOBID_FIELD_NUMBER: builtins.int
    jobId: builtins.str
    def __init__(
        self,
        *,
        jobId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["jobId", b"jobId"]) -> None: ...

global___SubmitJobResponse = SubmitJobResponse

@typing.final
class GetJobStatusRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOBID_FIELD_NUMBER: builtins.int
    jobId: builtins.str
    def __init__(
        self,
        *,
        jobId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["jobId", b"jobId"]) -> None: ...

global___GetJobStatusRequest = GetJobStatusRequest

@typing.final
class GetJobStatusResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    STATUS_FIELD_NUMBER: builtins.int
    status: global___JobStatus.ValueType
    def __init__(
        self,
        *,
        status: global___JobStatus.ValueType = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["status", b"status"]) -> None: ...

global___GetJobStatusResponse = GetJobStatusResponse

@typing.final
class CancelJobRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    JOBID_FIELD_NUMBER: builtins.int
    jobId: builtins.str
    def __init__(
        self,
        *,
        jobId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["jobId", b"jobId"]) -> None: ...

global___CancelJobRequest = CancelJobRequest

@typing.final
class GetPrinterInfoRequest(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    PRINTERID_FIELD_NUMBER: builtins.int
    printerId: builtins.str
    def __init__(
        self,
        *,
        printerId: builtins.str = ...,
    ) -> None: ...
    def ClearField(self, field_name: typing.Literal["printerId", b"printerId"]) -> None: ...

global___GetPrinterInfoRequest = GetPrinterInfoRequest

@typing.final
class GetPrinterInfoResponse(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    CAPABILITIES_FIELD_NUMBER: builtins.int
    STATUS_FIELD_NUMBER: builtins.int
    status: global___PrinterStatus.ValueType
    @property
    def capabilities(self) -> global___Capabilities: ...
    def __init__(
        self,
        *,
        capabilities: global___Capabilities | None = ...,
        status: global___PrinterStatus.ValueType = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["capabilities", b"capabilities"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["capabilities", b"capabilities", "status", b"status"]) -> None: ...

global___GetPrinterInfoResponse = GetPrinterInfoResponse

@typing.final
class Capabilities(google.protobuf.message.Message):
    DESCRIPTOR: google.protobuf.descriptor.Descriptor

    VERSION_FIELD_NUMBER: builtins.int
    PRINTER_FIELD_NUMBER: builtins.int
    version: builtins.str
    @property
    def printer(self) -> google.protobuf.struct_pb2.Struct: ...
    def __init__(
        self,
        *,
        version: builtins.str = ...,
        printer: google.protobuf.struct_pb2.Struct | None = ...,
    ) -> None: ...
    def HasField(self, field_name: typing.Literal["printer", b"printer"]) -> builtins.bool: ...
    def ClearField(self, field_name: typing.Literal["printer", b"printer", "version", b"version"]) -> None: ...

global___Capabilities = Capabilities
